variable "region" {}
variable "ecr_repository" {}
variable "ecs_task_family_name" {}
variable "container_port" {}
variable "subnets" {}
variable "acc_id" {}
variable "image_tag" {}
variable "vpc_id" {}
variable "branch" {}
variable "domain" {}
variable "zone_id" {}
variable "cname" {}
variable "health_check_path" {}
variable "alb_tls_cert_arn" {}
variable "buildspec_file" {}
variable "repo_id" {}
variable "compute_type" {}
variable "codebuild_image" {}
variable "type" {}
variable "min_capacity" {}
variable "max_capacity" {}
variable "desired_capacity" {}
variable "cpu" {}
variable "memory" {}
variable "docker_filename" {}